import type { ThemeConfig } from "antd";

const color = {
  primary: "#12765b",
  primarySubtle: "#e8f4ef",
  primaryHover: "#0d5d47",
  primaryActive: "#0c5340",
  warning: "#b36618",
  warningText: "#8b5415",
  warningSubtle: "#fff3df",
  danger: "#b54238",
  dangerSubtle: "#fdecea",
  info: "#3266a8",
  infoSubtle: "#eaf1fb",
  text: "#15211d",
  textSecondary: "#66736d",
  textMuted: "#7f8b85",
  page: "#f5f7f5",
  container: "#ffffff",
  elevated: "#fbfcfb",
  disabled: "#eff2ef",
  tableHead: "#f5f8f6",
  tableHover: "#f8fcfa",
  border: "#d8e2dc",
  borderSecondary: "#e8eeea",
} as const;

/** SEEKWAY 标准组件主题；业务页面不得重复定义同义视觉值。 */
export const seekwayAntdTheme = {
  cssVar: {
    prefix: "seekway",
  },
  token: {
    colorPrimary: color.primary,
    colorPrimaryBg: color.primarySubtle,
    colorPrimaryHover: color.primaryHover,
    colorPrimaryActive: color.primaryActive,
    colorLink: color.primary,
    colorSuccess: color.primary,
    colorSuccessBg: color.primarySubtle,
    colorWarning: color.warning,
    colorWarningText: color.warningText,
    colorWarningBg: color.warningSubtle,
    colorError: color.danger,
    colorErrorBg: color.dangerSubtle,
    colorInfo: color.info,
    colorInfoBg: color.infoSubtle,
    colorTextBase: color.text,
    colorText: color.text,
    colorTextSecondary: color.textSecondary,
    colorTextTertiary: color.textMuted,
    colorTextDisabled: color.textMuted,
    colorBgBase: color.container,
    colorBgLayout: color.page,
    colorBgContainer: color.container,
    colorBgElevated: color.elevated,
    colorBgContainerDisabled: color.disabled,
    colorFillAlter: color.tableHead,
    colorBorder: color.border,
    colorBorderSecondary: color.borderSecondary,
    fontFamily:
      'Inter, "Noto Sans SC", "Microsoft YaHei", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 14,
    borderRadius: 8,
    borderRadiusSM: 7,
    borderRadiusLG: 12,
    controlHeight: 38,
    controlHeightSM: 34,
    controlHeightLG: 40,
    sizeUnit: 4,
    sizeStep: 4,
    boxShadow:
      "0 1px 2px rgb(19 34 29 / 5%), 0 8px 20px rgb(19 34 29 / 4%)",
    boxShadowSecondary: "0 20px 70px rgb(19 34 29 / 18%)",
  },
  components: {
    Layout: {
      bodyBg: color.page,
      headerBg: "var(--color-surface-topbar)",
      siderBg: "var(--color-surface-sidebar)",
    },
    Menu: {
      darkItemBg: "var(--color-surface-sidebar)",
      darkSubMenuItemBg: "var(--color-surface-sidebar-end)",
      darkItemColor: "var(--color-text-sidebar-secondary)",
      darkItemHoverBg: "var(--color-surface-sidebar-hover)",
      darkItemSelectedBg: "var(--color-surface-sidebar-active)",
      darkItemSelectedColor: "var(--color-text-sidebar-primary)",
      darkGroupTitleColor: "var(--color-text-sidebar-muted)",
    },
    Table: {
      headerBg: color.tableHead,
      headerColor: color.text,
      headerSplitColor: color.borderSecondary,
      rowHoverBg: color.tableHover,
      cellPaddingBlock: 12,
    },
  },
} satisfies ThemeConfig;
